apiVersion: v1
kind: Pod
metadata:
  name: hello-node  # 동일한 namespace 상에서 유니크한 값
  labels:
    app: hello-node # .metadata.labels.app: 오브젝트를 식별하는 레이블을 설정
spec:
  containers:
  - name: hello-node
    image: hello-node:v1
    imagePullPolicy: Never
    ports:
      - containerPort: 8080
  # nodeSelector:
  #   disktype: ssd

# $ kubectl apply -f [파일명]